### ISSUE TITLE
[ Bug ] Authorization is broken

### ISSUE THREAD

**Issue by daviskeene** [founders/startup-directory#13]
## Describe the bug
On both local and production environments, logging in with google does not work. Auth0 is getting different errors upon a successful and unsuccessful login attempt.

## To Reproduce
1. Go to startup directory home page.
2. Log in with google.
3. Experience error :p

## Expected behavior
Upon a successful login attempt, users should be redirected to the homepage of the directory with their account enabled. On an unsuccessful login, users should see the error page.

### Localhost, successful attempt
<img width="545" alt="Screen Shot 2021-09-14 at 11 44 46 AM" src="https://user-images.githubusercontent.com/14897590/133299340-75cac176-8159-4db8-bbde-48233bc81eaf.png">

### Localhost, unsuccessful attempt
<img width="915" alt="Screen Shot 2021-09-14 at 11 45 37 AM" src="https://user-images.githubusercontent.com/14897590/133299449-08ba0c49-9f9d-4928-9f9d-c47a9a061a5a.png">

### Prod, successful attempt
<img width="639" alt="Screen Shot 2021-09-14 at 12 52 04 PM" src="https://user-images.githubusercontent.com/14897590/133308605-10eb543e-d990-42f4-8e5b-37974d66632f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.5.7
 - Browser: Google Chrome
 - Version: 93.0.4577.63

## Additional context
Seems like auth was working up until we changed our domain. For production it seems like we should just update the list of callback URLs to include `directory.foundersillinois.org`, but it doesn't explain the new errors happening on a local login attempt.

[09/14/2021 12:50pm] I updated the `AUTH0_BASE_URL` env variable in vercel which got rid of the callback error happening on prod. Still stuck on this `access_denied (Cannot read property 'split' of undefined)` issue though.

**Comment by SirajChokshi** [comment]
Resolved on Auth0 rule.
