### ISSUE TITLE
[ Enhancement ] Add Array field to include custom labels, such as `TEC`, `iVenture`, `Zero2One`,  etc.

### ISSUE THREAD

**Issue by daviskeene** [founders/startup-directory#16]
## Description
The startup directory is all about visibility into entrepreneurship. To encourage this, we want to make it so that when users are scrolling through the directory, they can see all of the entrepreneurship resources that are available to them. To do this, let's create an `Enum` that contains a few values for labels that define Startup Ecosystems at UIUC. Next, we'll create a new `Array` field that stores a list of these `Enum`s, and render these custom labels on the corresponding `OrgCard`.

## Steps to Solve
1. Modify `models/Org.js` to create a new `Enum` with a few entrepreneurship resources on campus. A few good places to start are `TEC`, `iVenture`, `Zero2One`, and `Founders`. (We could also do `54` and `Forge`).
2. Include a new `Array` / `Set` field that will store a list of these `Enum`s.
3. Modify `components/Form.js` to include a way for startups to select from these fields. The corresponding `Array` field in the `Org` document should be updated to contain a list of all selected values.
4. Modify `components/OrgCard.js` to display new `Tags` if these properties exist for Organizations.

## Definition of Done
This issue will be marked as `Closed` when a PR is approved that accomplishes the following:
- A startup can click on their `Account` and select from a set of values that represent the organizations that they're part of / resources that they've used.
- These new properties are displayed on their `OrgCard`.

**Comment by SirajChokshi** [comment]
Maybe we can use an array/set that is backed by an enum instead of adding more boolean fields to be more scalable 👍
